on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v2
      - uses: actions/checkout@v4

      - name: build
        run: |
          docker buildx build --pull --platform linux/amd64,linux/arm64 .

      - name: Publish to GitHub Packages Container registry
        run: |
          printenv PASSWORD | docker login --username "$USERNAME" --password-stdin ghcr.io
          docker buildx build --push --platform linux/amd64,linux/arm64 -t "ghcr.io/$USERNAME/minimum-elf:latest" .
          docker logout
        env:
          USERNAME: ${{ github.repository_owner }}
          PASSWORD: ${{ secrets.GITHUB_TOKEN }}
